../../kolumny: output line 1: error procesing file '../input1.txt' when evaluating python-expression '(column(4))' in using in phase2
../../kolumny: Error when procesing file '../input1.txt' line 1 in phase2
../../kolumny: Used using [{'variable': None, 'type': 'python-expression', 'columns': '(column(4))', 'not_print': False}]
Exception occured when processing output line 1 at phase2, pass number 1: 'None'
Traceback (most recent call last):
  File "../../kolumny", line xxx, in <module>
    for row in kk:
  File "../../kolumny", line xxx, in go
    v = eval(c, globals(), local_variables)
  File "<string>", line 1, in <module>
  File "../../kolumny", line xxx, in column_function
    raise NameError("trying to access invalid column number %d in file '%s' line %d, only %d columns available" % (x, a["file_name"], a["current_line_number"], len(l)))
NameError: trying to access invalid column number 4 in file '../input1.txt' line 1, only 3 columns available
